# Generated by Django 4.2 on 2023-05-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0004_address_connections_connection_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connections',
            name='connection_type',
            field=models.CharField(choices=[('prepaid', 'Prepaid'), ('postpaid', 'Postpaid')], max_length=20),
        ),
    ]
