# Generated by Django 4.2 on 2023-05-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0005_alter_connections_connection_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='connections',
            name='profile_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
