# Generated by Django 4.1.9 on 2023-06-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0008_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mob_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
