# Generated by Django 4.1.9 on 2023-06-19 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN', '0008_alter_subscription_is_active'),
        ('USER', '0010_remove_address_user_user_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ADMIN.subscription'),
        ),
    ]
